from pathlib import Path


GAME_TITLE = "Sob Análise"

VIRTUAL_WIDTH = 1920
VIRTUAL_HEIGHT = 1080

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TARGET_FPS = 60

CAMERA_ZOOM = 1.008
CAMERA_PARALLAX_X = 5.0
CAMERA_PARALLAX_Y = 3.0
CAMERA_BREATH_X = 1.4
CAMERA_BREATH_Y = 1.0
CAMERA_RESPONSE = 2.4

BASE_DIR = Path(__file__).resolve().parents[2]
ASSETS_DIR = BASE_DIR / "assets"
USER_SETTINGS_PATH = BASE_DIR / "data" / "user_settings.json"

LETTERBOX_COLOR = (0, 0, 0)
DEBUG_UI = False
DEBUG_LAYOUT_RECTS = False
